FROM nvcr.io/nvidia/tensorflow:21.05-tf2-py3

MAINTAINER Maja Franz <maja.franz@othr.de>

# Add user
RUN useradd -m -G sudo -s /bin/bash repro && echo "repro:repro" | chpasswd
RUN usermod -a -G staff repro
WORKDIR /home/repro

# Add directory to home directory
ADD --chown=repro:repro . /home/repro

# install required packages
#RUN python -m pip install --upgrade pip
#RUN pip3 install -r requirements.txt

# install R and R-packages for plotting
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install r-base texlive-latex-base \
    r-cran-devtools -y

RUN R -e "install.packages('ggplot2')"
RUN R -e "install.packages('tikzDevice')"
RUN R -e "install.packages('ggh4x')"

USER repro
